#ANN

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import os


df=pd.read_csv('xfood_test.csv')
df_stone=df.copy()
df_stone=df_stone[['wFood1','wFood2','wFood3','wFood4','pFood1','pFood2','pFood3','pFood4','xFood']]
df_stone['StonePriceIndex']= np.log(df_stone['xFood']) - np.log((df_stone['wFood1']*df_stone['pFood1'])+ (df_stone['wFood2']*df_stone['pFood2'])+(df_stone['wFood3']*df_stone['pFood3'])+(df_stone['wFood4']*df_stone['pFood4']))
df_stone


df1=df_stone.copy()
df1

df1['pFood1']= np.log(df1['pFood1'])
df1['pFood2']= np.log(df1['pFood2'])
df1['pFood3']= np.log(df1['pFood3'])
df1['pFood4']= np.log(df1['pFood4'])
df1

df1.columns

# Define input and output columns
input_cols = ['pFood1' , 'pFood2' , 'pFood3','pFood4','StonePriceIndex']
output_cols = ['wFood1' , 'wFood2' , 'wFood3' , 'wFood4']

# Split the data into input and output
X = df1[input_cols].values
Y = df1[output_cols].values

# Split into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(25, 5) (7, 5) (25, 4) (7, 4)


In [ ]:
# Define the model architecture
model = Sequential([
    Dense(5, activation='relu', input_shape=(5,)),
    Dense(32, activation='relu'),
    Dense(4)  # Output layer with 4 units for BudgetS_1 to BudgetS_4
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Print the model summary
model.summary()


C:\Users\agarw\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 5)                   │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 32)                  │             192 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 4)                   │             132 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 354 (1.38 KB)

 Trainable params: 354 (1.38 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Train the model
history = model.fit(X_train, Y_train, epochs=50, batch_size=5, verbose=1, validation_data=(X_test, Y_test))


Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 87ms/step - loss: 0.4501 - val_loss: 0.3557
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3301 - val_loss: 0.2573
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.2321 - val_loss: 0.1833
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1710 - val_loss: 0.1292
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1186 - val_loss: 0.0908
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0837 - val_loss: 0.0639
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0578 - val_loss: 0.0451
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0410 - val_loss: 0.0319
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0297 - val_loss: 0.0227
Epoch 10/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0212 - val_loss: 0.0161
Epoch 11/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0146 - val_loss: 0.0115
Epoch 12/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0105 - val_loss: 0.0082
E

In [ ]:
X_test.shape

(7, 5)

In [ ]:
Y_test.shape

(7, 4)

In [ ]:
X_test[2,:].reshape(1,5)

array([[4.20469262, 4.18052226, 4.2822063 , 4.27805404, 1.66399976]])

In [ ]:
Y_test[2,:].reshape(1,4)

array([[0.298, 0.201, 0.139, 0.362]])

In [ ]:
model.predict(X_test[2,:].reshape(1,5))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step


array([[0.29594645, 0.17828667, 0.13808715, 0.34215778]], dtype=float32)

In [ ]:
# Save the entire model
model.save(r'model.h5')

# Load the entire model
new_model = tf.keras.models.load_model(r'model.h5')

In [ ]:
new_model.predict(X_test[2,:].reshape(1,5))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step


array([[0.29594645, 0.17828667, 0.13808715, 0.34215778]], dtype=float32)